"""add_debitcard_table

Revision ID: 92785daea096
Revises: b8d0ecf899e3
Create Date: 2026-01-01 14:23:18.527019

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '92785daea096'
down_revision: str | Sequence[str] | None = 'b8d0ecf899e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
