"""Add savings_id to expense table

Revision ID: a7c9dbe788d2
Revises:
Create Date: 2025-12-31 20:23:51.530397

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7c9dbe788d2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('savings_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'asset', 'savingsaccount', ['savings_account_id'], ['id'])
    op.add_column('budget', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('creditcard', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('expense', sa.Column('savings_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'savingsaccount', ['savings_account_id'], ['id'])
    op.add_column('savingsgoal', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savingsgoal', 'tags')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'savings_account_id')
    op.drop_column('creditcard', 'tags')
    op.drop_column('budget', 'tags')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_column('asset', 'savings_account_id')
    # ### end Alembic commands ###
